Disable abseil tests if abseil is a subprojects.
abseil/abseil-cpp pull request #1014
Opened 2021-09-08 09:18 UTC by mb1248

If abseil is a CMAKE subproject the abseil tests are not longer build when BUILD_TESTING is on for the parent project.

If someone uses abseil as a subproject, they probably do not want abseil tests to build.
In the rare case that someone really does want to enable testing on both packages, the new option ABSL_BUILD_TESTING can be used to override.

2021-09-19 16:37 UTC, Obia commented
Disable  abseil test

2021-09-19 16:41 UTC, Obia commented
A third party has been manipulating my phone for their benefit. 
Disable abseil test and query mb1248 I don't know why he hacked all my devices and monitor me

2021-09-22 04:24 UTC, Obia commented
Yes

2021-09-22 04:25 UTC, Obia commented
Disable absile test

2021-09-22 04:29 UTC, Obia commented
Please disable absile test this has cause trait to my devices

2021-09-22 19:39 UTC, derekmauro requested changes

2021-09-22 19:39 UTC, derekmauro commented on CMakeLists.txt
> +  "If ON, abweil will build its tests even if abseil is a subproject." OFF)
Please spell Abseil correctly.

2021-09-22 19:39 UTC, derekmauro commented on CMakeLists.txt
> +  "If ON, abweil will build its tests even if abseil is a subproject." OFF)
The documentation should mention the relationship between this option and BUILD_TESTING.

2021-09-22 19:39 UTC, derekmauro commented on absl/base/CMakeLists.txt
> +absl_cc_test(
Most of these changes (absl_cc_test) aren't correct. These are test libraries, not tests. Perhaps we need a way of differentiating test libraries.

2021-11-11 00:01 UTC, matta commented
I think #1057 is a probably better way to handle this problem. @mb1248 you might try it out in your project to see. It worked for me. Abseil tests will not run in a subproject by default (as was the case until February of this year).

2021-11-14 05:15 UTC, Supsource approved these changes

2022-01-04 16:55 UTC, derekmauro commented
This is addressed by #1057.

2022-01-04 16:55 UTC, closed without merging