Use freebsd macro definition for ElfW macro for compatibility.
abseil/abseil-cpp pull request #1037
Opened 2021-10-07 16:33 UTC by yesudeep

Addresses: https://github.com/abseil/abseil-cpp/issues/1024

The `ElfW()` macro was added to `elf_generic.h` recently and as such may be absent most current releases of FreeBSD.

See: https://github.com/freebsd/freebsd-src/blob/34e7e4b6a059eee5e4e3e34de5b9d5f0d6e589f9/sys/sys/elf_generic.h#L60

There are other build issues on FreeBSD. I'll address them soonish in other PRs.

@derekmauro @EmployedRussian

2021-10-07 16:34 UTC, yesudeep commented
Sent a new PR with clang-autoformatting disabled in the editor.

2021-10-07 17:03 UTC, EmployedRussian requested changes
This looks good to me, except the `aux` vs. `auxv` typo is back.

2021-10-07 17:03 UTC, EmployedRussian commented on absl/debugging/internal/vdso_support.cc
> +using Elf64_aux_t = Elf64_Auxinfo;
s/aux/auxv/

2021-10-07 17:06 UTC, yesudeep commented on absl/debugging/internal/vdso_support.cc
> +using Elf64_aux_t = Elf64_Auxinfo;
I should have drank the coffee lol.

2021-10-08 14:50 UTC, derekmauro approved these changes

2021-10-08 14:50 UTC, merged

2021-11-16 08:59 UTC, danfe commented
> There are other build issues on FreeBSD. I'll address them soonish in other PRs.

What are those issues?  We do need to patch the `absl/base/internal/unscaledcycleclock.cc` file in FreeBSD port, but otherwise it all seems file so far.  We also bump the C++ standard because of #819.