Exclude #pragma intrinsic(_umul128) from ARM64EC
abseil/abseil-cpp pull request #1134
Opened 2022-03-16 06:16 UTC by mcfi

ARM64EC is a Microsoft-designed ARM64 ABI compatible with AMD64 applications on ARM64 Windows 11.  The ARM64EC does not support _umul128 as an intrinsic, but an inline function. Therefore, exclude #pragma intrinsic(_umul128) from ARM64EC compilation.

2022-03-16 18:32 UTC, derekmauro requested changes

2022-03-16 18:32 UTC, derekmauro commented on absl/base/internal/unscaledcycleclock.cc
> +#if !defined(_M_ARM64EC)
Using emulated `__rdtsc` on ARM seems sub-optimal. `UnscaledCycleClock` is an optional interface used by `CycleClock` when it is available. Have a look at `unscaledcycleclock.h`. I think it would be better to just disable this interface when `_M_ARM64EC` is defined.

2022-03-16 18:32 UTC, derekmauro commented on absl/numeric/int128.h
>  #pragma intrinsic(_umul128)
I have a similar concern here. I wonder if the portable code is faster than the emulated intrinsic.

2022-03-16 18:38 UTC, mcfi commented on absl/base/internal/unscaledcycleclock.cc
> +#if !defined(_M_ARM64EC)
__rdstc on ARM64EC is implemented as _ReadStatusReg(ARM64_PMCCNTR_EL0), which is not emulated.

2022-03-16 19:00 UTC, derekmauro commented on absl/base/internal/unscaledcycleclock.cc
> +#if !defined(_M_ARM64EC)
I don't think this changes anything. In `unscaledcycleclock.h` there is code that says "UnscaledCycleClock frequency is the same as CPU frequency", which isn't true of all ARM processors. It is also the case that `UnscaledCycleClock` is really only necessary on our production platform, which doesn't use `_M_ARM64EC`. I think it better to just disable this interface.

2022-03-17 17:20 UTC, mcfi commented on absl/base/internal/unscaledcycleclock.cc
> +#if !defined(_M_ARM64EC)
Ok, sounds good, I'll abandon this PR and send a new one. Thanks.

2022-03-17 17:21 UTC, closed without merging

2022-03-17 19:41 UTC, mcfi commented on absl/base/internal/unscaledcycleclock.cc
> +#if !defined(_M_ARM64EC)
New PR here https://github.com/abseil/abseil-cpp/pull/1135