fix build with uclibc-ng
abseil/abseil-cpp pull request #1145
Opened 2022-03-23 21:03 UTC by ffontaine

uclibc-ng doesn't provide `getauxval` which results in the following build failure on arm or ppc with any user of abseil-cpp such as grpc:

```
/home/buildroot/autobuild/instance-0/output-1/host/opt/ext-toolchain/bin/../lib/gcc/arm-buildroot-linux-uclibcgnueabi/10.3.0/../../../../arm-buildroot-linux-uclibcgnueabi/bin/ld: /home/buildroot/autobuild/instance-0/output-1/host/arm-buildroot-linux-uclibcgnueabi/sysroot/usr/lib/libabsl_random_internal_randen_hwaes.so.2111.0.0: undefined reference to `getauxval'
```

To fix this build failure, check that `getauxval` symbol is available before setting `ABSL_HAVE_GETAUXVAL`

Fixes:
 - http://autobuild.buildroot.org/results/775f3ca3dedebff29e212b29dfa896b7613b7a02

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

2022-03-24 01:13 UTC, derekmauro requested changes
The change proposed in this PR would break our Bazel build (which is our primary build system).

2022-03-24 07:23 UTC, ffontaine commented
Indeed, do you know the counterpart of cmake's `check_symbol_exists` (or autotools's `AC_CHECK_FUNCS`) in Bazel buildsystem?

2022-03-24 13:46 UTC, derekmauro commented
There is no equivalent in Bazel. Does using `__UCLIBC__` work?

2022-03-24 13:53 UTC, ffontaine commented
Yes, `__UCLIBC__ ` should also work. I'll update the PR.

2022-03-30 17:35 UTC, ffontaine commented
Do you have additional comments on this PR?

2022-03-30 17:40 UTC, derekmauro commented
I didn't realized you updated the PR. This should be fine, I will import it soon.

2022-03-30 19:56 UTC, merged