Convert empty constructors to default ones
abseil/abseil-cpp pull request #1394
Opened 2023-02-16 17:36 UTC by AtariDreams

These make the changed constructors match closer to the other ones that are default.

2023-02-16 20:35 UTC, derekmauro requested changes

2023-02-16 20:35 UTC, derekmauro commented on absl/time/internal/cctz/src/time_zone_if.cc
> +TimeZoneIf::~TimeZoneIf() = default;
The changes to all files under `absl/time/internal/cctz/` need to be sent to https://github.com/google/cctz. We will then import these changes.

2023-02-17 15:23 UTC, AtariDreams commented
@derekmauro Done!

2023-02-17 15:31 UTC, derekmauro approved these changes
Looks good, thanks. I have to run this and some of your other changes though our internal work flow to get them submitted, so please be patient. This should be merged soon.

2023-02-21 20:17 UTC, merged