Use const and static for member functions
abseil/abseil-cpp pull request #1395
Opened 2023-02-16 17:36 UTC by AtariDreams

This shows that these are member functions that do not modify a class's data.

2023-02-16 20:38 UTC, derekmauro requested changes

2023-02-16 20:38 UTC, derekmauro commented on absl/strings/string_view.cc
> +      if ((o.flags() & std::ostream::adjustfield) == std::ostream::left) {
This change doesn't seem consistent with the rest of the changes in this change. I would have to ask that we avoid the churn for this one.

2023-02-17 19:55 UTC, AtariDreams commented
Addressed! @derekmauro

2023-02-23 16:48 UTC, derekmauro requested changes

2023-02-23 16:48 UTC, derekmauro commented on absl/crc/internal/crc32c_inline.h
> +inline bool ExtendCrc32cInline(const uint32_t* crc, const char* p, size_t n) {
Please see line 56. This change doesn't build.

2023-03-06 17:10 UTC, AtariDreams commented
Fixed! @derekmauro

2023-03-08 20:10 UTC, merged