Fetch local_config_cc from rules_cc instead of bazel
abseil/abseil-cpp pull request #1773
Opened 2024-10-17 22:18 UTC by keith

With bazel 8.x cc_configure.bzl has moved to rules_cc

2024-10-21 12:18 UTC, derekmauro requested changes
Was this tested with any version of Bazel? I haven't tried Bazel 8, but Bazel 7 gives
```
(01:08:18) Analyzing: 510 targets (26 packages loaded, 0 targets configured)
[0 / 1] checking cached actions
(01:08:19) ERROR: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/7eca63b212bb77491fc771313ed1b4be/external/rules_cc~0.0.13/cc/extensions.bzl", line 21, column 34, in _cc_configure_extension_impl
		return ctx.extension_metadata(reproducible = True)
Error in extension_metadata: extension_metadata() got unexpected keyword argument 'reproducible'
(01:08:19) Analyzing: 510 targets (63 packages loaded, 628 targets configured)
[1 / 1] checking cached actions
(01:08:20) WARNING: errors encountered while analyzing target '//absl/log:log_macro_hygiene_test', it will not be built.
error evaluating module extension cc_configure_extension in @@rules_cc~0.0.13//cc:extensions.bzl
```

Is there a way to make this change in a backwards compatible way?

2024-10-21 18:03 UTC, keith commented
this requires bazel 7.1.0+, so you must be testing with 7.0.0? it would probably be easier to rely on that point release vs trying to make this backwards compatible unless there's a strong reason not to

2024-11-13 18:44 UTC, keith commented
fixed upstream instead https://github.com/bazelbuild/bazel/pull/24154

2024-11-13 18:44 UTC, closed without merging

2024-12-06 18:01 UTC, keith commented
nvm fixed here by https://github.com/abseil/abseil-cpp/commit/9e3b68ac3b328212e4ad7baada1523a05f615dde