absl::meta Fix test alignment conformance for VS 2017 >= 15.8 (#193)
abseil/abseil-cpp pull request #196
Opened 2018-10-19 07:13 UTC by Mizux

2018-10-22 15:27 UTC, JonathanDCohen requested changes

2018-10-22 15:27 UTC, JonathanDCohen commented on CMakeLists.txt
> +    /D_ENABLE_EXTENDED_ALIGNED_STORAGE
We need this in copts.bzl as well.  Do we have a test exercising this flag?  Otherwise I'd rather not add a build flag without an associated failure it's fixing.

2018-10-22 19:21 UTC, Mizux commented on CMakeLists.txt
> +    /D_ENABLE_EXTENDED_ALIGNED_STORAGE
for /D_ENABLE_EXTENDED_ALIGNED_STORAGE, yes in the appveyor CI it fail that's why I put it in the PR then I was requested to split in differents CL....

2018-10-23 20:28 UTC, JonathanDCohen commented on CMakeLists.txt
> +    /D_ENABLE_EXTENDED_ALIGNED_STORAGE
cool, lgtm.  Can we put that into copts.bzl as well, though?

2018-10-24 14:39 UTC, Mizux commented
Can we first Merge PR #197 so I can rebase this work on it and so will should see this error gone. (i.e. kind of Test Driven Development (e.d. here the test is just to try to build on windows...))

2018-10-24 19:42 UTC, JonathanDCohen approved these changes
lgtm modulo a minor nit

2018-10-24 19:42 UTC, JonathanDCohen commented on CMakeLists.txt
> +    /D_CRT_SECURE_NO_WARNINGS /D_SCL_SECURE_NO_WARNINGS
nit: please put these on separate lines

2018-10-24 19:57 UTC, Mizux commented on CMakeLists.txt
> +    /D_CRT_SECURE_NO_WARNINGS /D_SCL_SECURE_NO_WARNINGS
done, fixup, push -f...

2018-10-24 19:58 UTC, Mizux commented
WAIT !vim config at home use tab -_-

2018-10-26 14:56 UTC, Mizux commented
Should be replaced by cl 218851993

2018-10-26 15:10 UTC, ahedberg commented
This was replicated internally and will be propagated to GitHub on our next push, so I'm going to close this PR.

2018-10-26 15:10 UTC, closed without merging