Fix CMakeLists.txt for container library
abseil/abseil-cpp pull request #200
Opened 2018-10-25 15:37 UTC by dongz9

Symbols defined in ``raw_hash_set.cc`` are missing from `absl::container``.

2018-10-25 18:00 UTC, JonathanDCohen requested changes

2018-10-25 18:00 UTC, JonathanDCohen commented on absl/container/CMakeLists.txt
> +list(APPEND CONTAINER_LIB_SRC
Let's just inline this

2018-10-25 18:00 UTC, JonathanDCohen commented on absl/container/CMakeLists.txt
> +absl_library(
Please use absl_cc_library, not absl_library

2018-10-25 18:09 UTC, 025116415 approved these changes

2018-10-26 13:06 UTC, Mizux commented
Seems #173 already fix it, did you rebase your commit on HEAD ?

2018-10-26 13:10 UTC, Mizux commented
And have been lost by c16d5557cd05119b5b7b1318ef778ebe3195b4a1 
@Abseil-team seriously, you should **really** reconsider your current workflow...

i.e. Start by never trust copybara (for google/or-tools we do a **manual** sync in/out)

2018-10-26 15:25 UTC, Mizux commented
@ahedberg to close and use cl/218856743 which reapply PR #173

2018-10-26 15:28 UTC, closed without merging