Fix ABSL_HAVE_ALARM check on mingw
abseil/abseil-cpp pull request #341
Opened 2019-06-25 22:25 UTC by jtsylve

mingw compilers don't support alarm()

2019-06-26 05:58 UTC, EricWF commented
This looks good to me.
But please be aware that  we have test coverage on MinGW (nor is it officially supported).

Regardless, thank you for the patch. I'll merge it once I verify it internally.

2019-07-08 16:55 UTC, jtsylve commented
rebased against master

2019-07-23 23:33 UTC, suertreus requested changes

2019-07-23 23:33 UTC, suertreus commented on absl/base/config.h
> +// feature tests for mingw
Please explain in this comment why `ABSL_HAVE_ALARM` is not defined for `__MINGW32__`.  I realize you've copied the form of the preceding comments, but they're not very helpful and I'd like to do better.  The `__EMSCRIPTEN__` example below is better.

It looks to me like the right comment is:
```
// mingw32 doesn't provide alarm(2):
// https://osdn.net/projects/mingw/scm/git/mingw-org-wsl/blobs/5.2-trunk/mingwrt/include/unistd.h
// mingw-w64 provides a no-op implementation:
// https://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/mingw-w64-crt/misc/alarm.c
```

2019-09-09 17:07 UTC, shaindelschwartz commented
@jtsylve Would you like to follow up here? There's an open review comment that should be resolved before we merge this.

2019-09-30 21:56 UTC, suertreus approved these changes

2019-10-09 21:07 UTC, merged