Fix build on FreeBSD/powerpc
abseil/abseil-cpp pull request #616
Opened 2020-02-10 13:04 UTC by kgotlinux

Only glibc has __ppc_get_timebase(), __ppc_get_timebase_freq() and sys/platform/ppc.h. For TBR and TBR frequency, FreeBSD doesn't have equivalent functions.

2020-02-10 21:26 UTC, derekmauro commented on absl/base/internal/unscaledcycleclock.cc
> +  asm volatile(
I'm not sure this code is optimal. It looks like, for example, ppc64 has a way of getting the value in one instruction.

https://github.com/bminor/glibc/blob/5f72f9800b250410cad3abfeeb09469ef12b2438/sysdeps/powerpc/sys/platform/ppc.h#L26-L51

2020-02-10 21:40 UTC, derekmauro requested changes

2020-02-10 21:40 UTC, derekmauro commented on absl/base/internal/unscaledcycleclock.cc
> +  union { long long complete; unsigned int part[2]; } ticks;
Though you sometimes see it, type-punning through a union is undefined behavior in C++. See https://adriann.github.io/undefined_behavior.html for example.

2020-02-10 21:40 UTC, derekmauro commented on absl/base/internal/unscaledcycleclock.cc
> +  sysctlbyname("kern.timecounter.tc.timebase.frequency", &timebaseFrequency, &length, NULL, 0);
Can you cache this value using some sort of "once" initialization? I don't think Abseil calls the code at all, but other (internal) code calls it very often.

For various reasons you'll need to use `absl::base_internal::LowLevelCallOnce` in this context.

https://github.com/abseil/abseil-cpp/blob/bf78e977309c4cb946914b456404141ddac1c302/absl/base/call_once.h#L199-L208

2020-02-10 21:40 UTC, derekmauro commented on absl/base/internal/unscaledcycleclock.cc
> +  double timebaseFrequency = 0;
https://google.github.io/styleguide/cppguide.html#Variable_Names

Variable names are lower-case with underscore in Google C++ style.

2020-02-10 21:40 UTC, derekmauro commented on absl/base/internal/unscaledcycleclock.cc
> +  union { long long complete; unsigned int part[2]; } ticks;
https://google.github.io/styleguide/cppguide.html#Integer_Types

This is a case where you should use fixed-width integer types like `int64_t`.

2020-02-12 18:42 UTC, kgotlinux commented
Please check if it's ok now.

2020-02-20 00:04 UTC, derekmauro requested changes

2020-02-20 00:04 UTC, derekmauro commented on absl/base/internal/unscaledcycleclock.cc
> +#elif defined(__FreeBSD__)
Is this code portable? I think it will work on non-FreeBSD ppc platforms as well. Should this just be `#else`?

2020-02-20 00:04 UTC, derekmauro commented on absl/base/internal/unscaledcycleclock.cc
> +  size_t length = sizeof(timebase_frequency);
This can go inside the lambda.

2020-02-20 00:04 UTC, derekmauro commented on absl/base/internal/unscaledcycleclock.cc
> +#endif
We probably want an `#else` `#error` here.

2020-02-25 21:27 UTC, derekmauro commented
I pushed changes to your branch to resolve the comments.

2020-02-25 21:27 UTC, merged